### ISSUE TITLE
NetRadioPreset not working

### ISSUE THREAD

**Issue by SVallant** [ioBroker/ioBroker.onkyo#36]
Variable " NetRadioPreset" not working
Variable "RAW" = NPR01 ==> Working
Possible Error: main.js line 131 ??https://github.com/ioBroker/ioBroker.onkyo/blob/81c9b74c43b757ae317ed8824175dc0f1543b5df/main.js#L131

Number of Station should be 2 digits ....

**Comment by Eisbaeeer** [comment]
Is it working, if you send the command in raw mode?
Some models does not support Presets. Please check this.
Eisbaeeer

**Comment by sepp68** [comment]
Seems so .... ;-)
I use this js-Code in  a  script:
`createState('NetRadioPresetNr', "01"); 
var netRadioPresetNrId = "javascript.0.NetRadioPresetNr";

var commandStateId="onkyo.0.Device.RAW";
var commandNetRadioPreset = "NPR";
var commandNetRadioQuery = "NTIQSTN"

// bticino Kommunikation
on(netRadioPresetNrId, function (obj) {
    console.log("New netRadioPresetNr: " + obj.state.val);
    setState(commandStateId, commandNetRadioPreset + obj.state.val);
    // query after 2 Seconds
    setTimeout(function(){ 
        setState(commandStateId, commandNetRadioQuery);
        }, 2000);
});`

**Comment by Eisbaeeer** [comment]
He, he ;-)
This is not realy a bug, it´s by design.
 You have to define the HEX Value in two digits to the iobroker object. I tested with the newest version. If you define it like my screenshot, all will work fine. Please test it with putting the HEX value in two digits.
![NET-radio-preset](https://user-images.githubusercontent.com/4928271/63209733-2c9c5f00-c0e5-11e9-9b15-0a843e316223.PNG)
