### ISSUE TITLE
TX NR686

### ISSUE THREAD

**Issue by EvoXtheAnonym** [ioBroker/ioBroker.onkyo#46]
Zone 1:
Volume, power state and tune working well

Mute: wrong format, its shown as text, should be a logical state. After change also working well

InputSelect is working, a name (not number) would be nice.

Tuner Preset and Net Radio preset: No function

Device: Empty folder
Zone 2: Not testable, not connected.

**Comment by EvoXtheAnonym** [comment]
A option for Listen Modes (maybe buttons) and a player controller (pre-next-play-pause) would be very nice.

Thanks for your Work ;D Waiting a decade for such an adapter

**Comment by Apollon77** [comment]
I updated the command definitions on GitHub version tigether with other stuff, please check this version.

Update and restart adapter manually after update

**Comment by ice987987** [comment]
tested with Onkyo TX-NR656:
`onkyo.0.Device.RAW`: `AMTTG` -> sets Audio Muting Wrap-Around
`onkyo.0.Device.RAW`: `AMT01` -> sets Audio Muting On
`onkyo.0.Device.RAW`: `AMT00` -> sets Audio Muting Off
`onkyo.0.Zone1.Mute`: `true` -> sets Audio Muting On (Zone1)
`onkyo.0.Zone1.Mute`: `false` -> sets Audio Muting Off (Zone1)
Zone 2 and Zone 3 should work similar, but I can't test. I have only one Zone.

`onkyo.0.Zone1.InputSelect`:
`01`	sets VIDEO2 CBL/SAT
`02`	sets VIDEO3 GAME/TV
`03`	sets VIDEO4 AUX1(AUX)
`05`	sets VIDEO6 PC
`10`	sets DVD BD/DVD
`11`	sets STRM BOX
`12`	sets TV
`22`	sets PHONO
`23`	sets CD TV/CD
`24`	sets FM
`25`	sets AM
`26`	sets TUNER
`29`	sets USB/USB(Front)
`2B`	sets NETWORK NET
`2C`	sets USB(toggle)
`2E`	sets Bluetooth
`UP`	sets Selector Position Wrap-Around Up
`DOWN`	sets Selector Position Wrap-Around Down
`QSTN`	gets The Selector Position

`onkyo.0.Zone1.NetRadioPreset` : no function (or I dont' know how to use)?
`onkyo.0.Zone1.TunerPreset`: can not test due to missing connection in my installation
`onkyo.0.Device`: no longer empty

**Comment by Apollon77** [comment]
Thaat means? ;-) Issue solved? or still something open?

**Comment by ice987987** [comment]
In my point of view: issue solved, but I can‘t speak for @EvoXtheAnonym.
