### ISSUE TITLE
version > 1.

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.onkyo#49]
How to use the latest adapter? Where is the receiver control? How could you spoil the adapter like that?

**Comment by Eisbaeeer** [comment]
Hey, you are a crazy guy. Not answering my questions since 2 years and now pushing such issue. How are you the last 2 years? The community pushing me to get forward with your adapter, because you didn´t tell the community how to use your adapter. Actually the adapter supports Pioneer, too. If you will help to get the adapter in new dimensions, you are welcome.

**Comment by instalator** [comment]
Thank you, I don't need an adapter, I wrote my own for myself. [https://github.com/instalator/ioBroker.onkyo2](https://github.com/instalator/ioBroker.onkyo2)
